from pathlib import Path

CONFIG = {
    'dataset_path': Path('/kaggle/input/chest-xray-pneumonia/chest_xray'),
    'img_size': 128,
    'batch_size': 32,
    'num_clients': 5,
    'epochs': 5,
    'client_epochs': 2,
    'learning_rate': 0.0005,
    'non_iid_factors': [0.0, 0.3, 0.6, 0.9],
    'aggregation_methods': ['FedAvg', 'FedMedian', 'FedProx', 'FedTrimmedMean', 'FedNova', 'FedAdapt'],
    'results_dir': Path('/kaggle/working/results'),
    'model_prefix': 'chest_xray_model',
    'mu': 0.01,
    'early_stopping_patience': 3,
    'save_best_only': True,
    'metrics': ['accuracy'],
    'checkpoint_frequency': 5,
    'model_save_frequency': 5,
    'validation_frequency': 1,
    'use_mixed_precision': True,
    'use_gradient_clipping': True,
    'max_gradient_norm': 1.0,
    'use_learning_rate_scheduler': True,
    'lr_decay_factor': 0.9,
    'lr_decay_epochs': 2,
    'trimmed_mean_beta': 0.1,
    'tau': 0.01,
    'class_weights': {0: 1.0, 1: 1.0},
}